/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __VOLUMEDIAL_H_CFF4EBB1__
#define __VOLUMEDIAL_H_CFF4EBB1__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "../Binary Data/UI/knobs.h"


//==============================================================================
/**
*/
class Knob  : public Slider

{
public:
    //==============================================================================
    Knob();
    ~Knob();

	String getTextFromValue (double value);
	void setReadoutType(String type);
	//void Slider::PopupDisplayComponent::BubbleComponent::paint(Graphics& g);

    void paint (Graphics& g);

private:
    //==============================================================================

	Image knobImage,smallKnobImage;
	int frameWidth;
	String readoutType;
	String testReadout;

};

#endif  // __VOLUMEDIAL_H_CFF4EBB1__
