/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_AE42FDA5__
#define __PLUGINEDITOR_H_AE42FDA5__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "PluginProcessor.h"
// #include "Resources/Headers/Meters/LevelMeter.h"
#include "Headers/UI/Knob.h"
#include "Headers/UI/FancyButton.h"
#include "Headers/Binary Data/Backgrounds/thefunctionbackground.h"


//==============================================================================
/**
*/
class TheFunctionAudioProcessorEditor  : public AudioProcessorEditor,
										public SliderListener,
										public ButtonListener,					
										public Timer
{
public:
    TheFunctionAudioProcessorEditor (TheFunctionAudioProcessor* ownerFilter);
    ~TheFunctionAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
	void resized();
	void sliderValueChanged (Slider*);
	void buttonClicked (Button*);
	void timerCallback();

	Knob gainSlider;
	Knob gainLSlider;
	Knob gainRSlider;
	Knob panLSlider;
	Knob panRSlider;

	FancyButton phaseButtonL;
	FancyButton phaseButtonR;

	Image backgroundGUI;

	TheFunctionAudioProcessor* getProcessor() const
    {
        return static_cast <TheFunctionAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // __PLUGINEDITOR_H_AE42FDA5__
