/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINPROCESSOR_H_4FD11FCE__
#define __PLUGINPROCESSOR_H_4FD11FCE__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"


//==============================================================================
/**
*/
class TheFunctionAudioProcessor  : public AudioProcessor
{
public:
    //==============================================================================
    TheFunctionAudioProcessor();
    ~TheFunctionAudioProcessor();

    //==============================================================================
    void prepareToPlay (double sampleRate, int samplesPerBlock);
    void releaseResources();

    void processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages);

    //==============================================================================
    AudioProcessorEditor* createEditor();
    bool hasEditor() const;

    double getTailLengthSeconds() const { return 0.0; }

    //==============================================================================
    const String getName() const;

    int getNumParameters();

    float getParameter (int index);
    void setParameter (int index, float newValue);

    const String getParameterName (int index);
    const String getParameterText (int index);

    const String getInputChannelName (int channelIndex) const;
    const String getOutputChannelName (int channelIndex) const;
    bool isInputChannelStereoPair (int index) const;
    bool isOutputChannelStereoPair (int index) const;

    bool acceptsMidi() const;
    bool producesMidi() const;

    //==============================================================================
    int getNumPrograms();
    int getCurrentProgram();
    void setCurrentProgram (int index);
    const String getProgramName (int index);
    void changeProgramName (int index, const String& newName);


    //==============================================================================
    void getStateInformation (MemoryBlock& destData);
    void setStateInformation (const void* data, int sizeInBytes);

    bool silenceInProducesSilenceOut() const { return true; }

	enum Parameters
    {
        gainParam = 0,
		gainLParam,
		gainRParam,
		phaseLParam,
		phaseRParam,
		panLParam,
		panRParam,

        totalNumParams
    };

	float gain;
	float gainL;
	float gainR;

	float panL;
	float panR;

	float phaseL;
	float phaseR;

	//StringArray programNameArray;
	int currentPreset;
	int timeSinceChunkCalled;

private:
    //==============================================================================
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (TheFunctionAudioProcessor);
};

#endif  // __PLUGINPROCESSOR_H_4FD11FCE__
