#! /usr/bin/env python3
# -*- coding: utf-8 -*-

waveType = "square8";


for i in range(8):
	filepath = "./code";
	f = wave.open(filepath, "r");
	maxframes = f.getnframes();
	l = [];
	for frame in f.readframes(maxframes):
			l.append(str(frame));

	asString =  ", ".join(l) #or " ".join or "-".join or whatever
	with open(textfilePath, "w") as newfile:
		newfile.write(asString);

