/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __VOLUMEDIAL_H_CFF4EBB1__
#define __VOLUMEDIAL_H_CFF4EBB1__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "KnobsBI.h"


//==============================================================================
/**
*/
class Knob  :	public Slider


{
public:
    //==============================================================================
    Knob();
    ~Knob();

	//String getStringValue (double value);
	//void setReadoutType(String type);
	//void Slider::PopupDisplayComponent::BubbleComponent::paint(Graphics& g);

    void paint (Graphics& g);
	void setKnobType (int newType);
	void calculateReadoutValue();
	
	void setMIDILearn (bool isOn);
	bool getMIDILearn ();
	
	void setCCNumber(int newNumber);
	int getCCNumber();
	
	void setIsLearning(bool areWeLearning);


	
	
	enum KnobType
    {
		defaultType = 0,
        dualFilterType,
		mixType,
		panType,
		gainType,
		
        totalNumTypes
    };
	
	 //!!!!!!!!!!!!!

private:
    //==============================================================================

	Image filterKnobImage,mixKnobImage;
	int frameWidth;
	//Label readoutValue;
	//String readoutType;
	String readoutText;
	String CCText;
	int CCNumber;
	int knobType;
	bool MIDILearnIsActive;
	bool isLearning;
	

	



};

#endif  // __VOLUMEDIAL_H_CFF4EBB1__
