/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "MIDIButton.h"
#include "ButtonImage.h"


//==============================================================================
MIDIButton::MIDIButton()
{
	buttonImage = ImageFileFormat::loadFrom (ButtonImage::midilearnbutton_png, ButtonImage::midilearnbutton_pngSize);
	isLearning = false;
	
}

MIDIButton::~MIDIButton()
{
}

//==============================================================================
void MIDIButton::paint (Graphics& g)
{


	// Draw Image
	if (isLearning == false)
		g.drawImage (buttonImage, 0,0,112,41, 0, 0, 112, 41, false);
	else
		g.drawImage (buttonImage, 0,0,112,41, 0, 41, 112, 41, false);



}


void MIDIButton::setIsLearning(bool isItLearning)
{
	
	isLearning = isItLearning;
	repaint();
	
}
