/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __MIDIBUTTON__
#define __MIDIBUTTON__

#include "JuceHeader.h"
#include "JucePluginCharacteristics.h"
#include "KnobsBI.h"


//==============================================================================
/**	Button that toggles MIDI learn on and off. Very hacky, need to redo.**/

class MIDIButton  :	public TextButton
{
public:
    //==============================================================================
    MIDIButton();
    ~MIDIButton();

    void paint (Graphics& g);
	void setIsLearning(bool isItLearning);


private:
    //==============================================================================

	Image buttonImage;
	bool isLearning;
	
};

#endif  // __MIDIBUTTON__
